In [1]:
%load_ext autoreload
%autoreload 2

In [15]:
import torch
from UnarySim.sw.metric.metric import NormStability


In [16]:
normstb = NormStability(torch.tensor([[-0.5]]).cuda(), mode="bipolar", threshold=0.05).cuda()

Parameter containing:
tensor([0.0500])


In [136]:
a = torch.tensor([[1]]).type(torch.uint8)

In [104]:
a = torch.tensor([[0]]).type(torch.uint8)

In [105]:
print(a.size())

torch.Size([1, 1])


In [146]:
normstb.Monitor(a)
print(normstb.Report())
print(normstb.stability.Report())
print(normstb.max_stab)
print(normstb.stability.err)

tensor([[0.0533]])
tensor([[0.0500]])
tensor([[0.9375]])
tensor([[0.]])
