In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import torch
import numpy as np
import math
from UnarySim.sw.bitstream.gen import RNG, BSGen, BSRegen, SourceGen
from UnarySim.sw.metric.metric import Stability


In [3]:
stb = Stability(torch.tensor([0.5,0.75]), mode="bipolar", threshold=0.1)

In [22]:
a = torch.tensor([1,0]).type(torch.uint8)

In [25]:
a = torch.tensor([0,1]).type(torch.uint8)

In [29]:
stb.Monitor(a)
print(stb.err)
print(stb.stable_len)
print(stb.len)
print(stb.Report())

tensor([-0.1190, -0.1310])
tensor([21., 21.])
21.0
tensor([0., 0.])
tensor([-0.1190, -0.1310])
tensor([21., 21.])
21.0
tensor([0., 0.])
