In [1]:
%load_ext autoreload
%autoreload 2

In [1]:
import torch
import UnaryComputingSim
import numpy as np
import math
from UnaryComputingSim.sw.components.rng import RNG
from UnaryComputingSim.sw.components.bsgen import BSGen, BSRegen, SourceGen
from UnaryComputingSim.sw.components.bsshuffle import SkewedSync
from UnaryComputingSim.sw.metric.metric import Correlation, ProgressivePrecision, Stability, NormStability


In [3]:
corr = Correlation([1])

In [21]:
a = torch.tensor([0]).type(torch.uint8)
b = torch.tensor([0]).type(torch.uint8)

In [22]:
a = torch.tensor([0]).type(torch.uint8)
b = torch.tensor([1]).type(torch.uint8)

In [23]:
a = torch.tensor([1]).type(torch.uint8)
b = torch.tensor([0]).type(torch.uint8)

In [24]:
a = torch.tensor([1]).type(torch.uint8)
b = torch.tensor([1]).type(torch.uint8)

In [25]:
corr.Monitor(a,b)
# print("d", corr.paired_00_d)
# print("c", corr.paired_01_c)
# print("b", corr.paired_10_b)
# print("a", corr.paired_11_a)

# print(corr.len)

cor = corr.Report()
print(cor)

tensor([0.])
tensor([0.])


In [2]:
stb = Stability(torch.tensor([0.5,0.75]), bipolar=False, threshold=0.1)

In [22]:
a = torch.tensor([1,0]).type(torch.uint8)

In [25]:
a = torch.tensor([0,1]).type(torch.uint8)

In [29]:
stb.Monitor(a)
print(stb.err)
print(stb.stable_len)
print(stb.len)
print(stb.Report())

tensor([-0.1190, -0.1310])
tensor([21., 21.])
21.0
tensor([0., 0.])
tensor([-0.1190, -0.1310])
tensor([21., 21.])
21.0
tensor([0., 0.])


In [32]:
a = torch.tensor([0, 1, 2])
a

tensor([0, 1, 2])

tensor([0, 1, 2])

In [33]:
a.numpy()

array([0, 1, 2])

array([0, 1, 2])

In [4]:
np.gcd(1, 2)

AttributeError: module 'numpy' has no attribute 'gcd'

AttributeError: module 'numpy' has no attribute 'gcd'

In [4]:
np.version.version

'1.14.3'

In [57]:
prob = 0.105
thd = 0.05
prob_min = prob - thd
prob_max = prob + thd
print(prob_min, prob, prob_max)
cur_len = 63
length = pow(2, math.ceil(math.log2(cur_len)))
print(prob_min*length, prob*length, prob_max*length)
for x in range(math.ceil(prob_min*length), math.ceil(prob_max*length)):
    x_gcd = math.gcd(x, length)
    print(x, x/length)
    print(length/x_gcd)

0.05499999999999999 0.105 0.155
3.5199999999999996 6.72 9.92
4 0.0625
16.0
5 0.078125
64.0
6 0.09375
32.0
7 0.109375
64.0
8 0.125
8.0
9 0.140625
64.0


In [58]:
a = torch.tensor([[0, 1, 2], [0, 1, 2]])

In [59]:
a

tensor([[0, 1, 2],
        [0, 1, 2]])

In [66]:
len(a.size())

2

In [24]:
a = torch.tensor([[1]]).type(torch.uint8)

In [25]:
a = torch.tensor([[0]]).type(torch.uint8)

In [26]:
normstb = NormStability(torch.tensor([[0.5]]), bipolar=False, threshold=0.05)

In [31]:
normstb.Monitor(a)
print(normstb.Report())
print(normstb.len)
print(normstb.stability.err)

tensor([[0.]])
5.0
tensor([[-0.5000]])


In [9]:
for x in range(1,1):
    print(x)

In [12]:
a[0]

tensor(0, dtype=torch.uint8)