In [1]:
%load_ext autoreload
%autoreload 2

In [134]:
import torch
import UnaryComputingSim
from UnaryComputingSim.sw.component.rng import RNG
from UnaryComputingSim.sw.component.bsgen import BSGen, BSRegen, SourceGen



In [135]:
rng = RNG(4, 2, "Sobol").Out()
print(rng)

rng1 = RNG(4, 2, "Race").Out()
print(rng1)

tensor([ 8,  4, 12,  6, 14,  2, 10,  5, 13,  1,  9,  3, 11,  7, 15,  7])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])


In [136]:
bs1 = BSGen(torch.tensor([14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14]), rng1)

In [137]:
bs1.Gen(rng1)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0], dtype=torch.int8)

In [138]:
bs2 = BSRegen(rng1.size(), 4, rng1)

In [139]:
bs2.Gen(torch.tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0]), torch.tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=torch.int8)

In [140]:
print(bs2.cnt)

tensor([9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 7, 7])


In [141]:
srcbin = SourceGen(torch.tensor([0.5, 0.7]), 8, "unipolar")
print(srcbin.Gen())

tensor([128, 179])


In [142]:
srcbin2 = SourceGen(torch.tensor([0.5, 0.7]), 8, "bipolar")
print(srcbin2.Gen())

tensor([192, 218])
