In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import torch
from UnarySim.sw.metric.metric import NormStability


In [3]:
normstb = NormStability(torch.tensor([[-0.5]]).cuda(), mode="bipolar", threshold=0.05).cuda()

In [4]:
a = torch.tensor([[1]]).type(torch.int8).cuda()

In [5]:
a = torch.tensor([[0]]).type(torch.int8).cuda()

In [6]:
print(a.size())

torch.Size([1, 1])


In [7]:
normstb.Monitor(a)
print(normstb())
print(normstb.threshold)
print(normstb.stability())
print(normstb.stability.len)
print("normstb.max_stab:", normstb.max_stab)
print(normstb.min_prob)
print(normstb.in_shape)

tensor([[nan]], device='cuda:0')
Parameter containing:
tensor([0.0500], device='cuda:0')
tensor([[0.]], device='cuda:0')
Parameter containing:
tensor([1.], device='cuda:0')
normstb.max_stab: tensor([[0.]], device='cuda:0')
Parameter containing:
tensor([[0.2250]], device='cuda:0')
torch.Size([1, 1])
