In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import torch
from UnarySim.sw.metric.metric import Correlation

In [15]:
corr = Correlation()

In [25]:
a = torch.tensor([0]).type(torch.uint8)
b = torch.tensor([0]).type(torch.uint8)

In [23]:
a = torch.tensor([0]).type(torch.uint8)
b = torch.tensor([1]).type(torch.uint8)

In [21]:
a = torch.tensor([1]).type(torch.uint8)
b = torch.tensor([0]).type(torch.uint8)

In [19]:
a = torch.tensor([1]).type(torch.uint8)
b = torch.tensor([1]).type(torch.uint8)

In [26]:
corr.Monitor(a,b)
print("d", corr.paired_00_d)
print("c", corr.paired_01_c)
print("b", corr.paired_10_b)
print("a", corr.paired_11_a)

cor = corr()
print(cor)

d Parameter containing:
tensor([1.])
c Parameter containing:
tensor([1.])
b Parameter containing:
tensor([1.])
a Parameter containing:
tensor([1.])
tensor([0.])
