In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import torch
from UnarySim.sw.bitstream.gen import RawScale

In [3]:
input = torch.randn([2, 3]).cuda()
print(input)
srcbin = RawScale(input, mode="unipolar", percentile=99).cuda()
print(srcbin)
print(srcbin())


tensor([[-1.5026, -0.4619, -1.2355],
        [ 0.1482, -0.4002,  0.3773]], device='cuda:0')
RawScale()
Parameter containing:
tensor([[0.0000, 0.5537, 0.1395],
        [0.8804, 0.5868, 1.0000]], device='cuda:0')


In [4]:
srcbin2 = RawScale(input, mode="bipolar")
print(srcbin2())

Parameter containing:
tensor([[-1.0000,  0.1072, -0.7158],
        [ 0.7563,  0.1729,  1.0000]], device='cuda:0')
