In [1]:
%load_ext autoreload
%autoreload 2

In [1]:
import torch
import UnarySim
from UnarySim.sw.bitstream.shuffle import SkewedSync


In [2]:
ss = SkewedSync(depth=3).cuda()

In [3]:
ss

SkewedSync()

In [4]:
print(ss.cnt)
print(ss.out_1)

Parameter containing:
tensor([-9223372036854775808], device='cuda:0')
Parameter containing:
tensor([0], device='cuda:0', dtype=torch.int8)


In [32]:
a = torch.tensor([[0, 0]]).type(torch.int8)
b = torch.tensor([[1, 1]]).type(torch.int8)

In [29]:
a = torch.tensor([[1, 1]]).type(torch.int8)
b = torch.tensor([[0, 0]]).type(torch.int8)

In [20]:
a = torch.tensor([[1, 1]]).type(torch.int8)
b = torch.tensor([[1, 1]]).type(torch.int8)

In [14]:
a = torch.tensor([[0, 0]]).type(torch.int8)
b = torch.tensor([[0, 0]]).type(torch.int8)

In [33]:
a = a.cuda()
print(a)
b = b.cuda()
print(b)


tensor([[0, 0]], device='cuda:0', dtype=torch.int8)
tensor([[1, 1]], device='cuda:0', dtype=torch.int8)


In [34]:
print(ss(a,b))
print(ss.cnt)
print(ss.out_1)

(Parameter containing:
tensor([[1, 1]], device='cuda:0', dtype=torch.int8), tensor([[1, 1]], device='cuda:0', dtype=torch.int8))
Parameter containing:
tensor([[0, 0]], device='cuda:0')
Parameter containing:
tensor([[1, 1]], device='cuda:0', dtype=torch.int8)
