In [5]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [40]:
import torch
from UnarySim.sw.bitstream.gen import RawScale

In [49]:
input = torch.randn([2, 3]).cuda()
print(input)
srcbin = RawScale(input, mode="unipolar", percentile=99).cuda()
print(srcbin)
print(srcbin())


tensor([[ 0.4986,  0.4862, -1.7096],
        [ 0.4994,  1.5458,  1.7705]], device='cuda:0')
RawScale()
Parameter containing:
tensor([[0.6297, 0.6261, 0.0000],
        [0.6299, 0.9359, 1.0000]], device='cuda:0')


In [50]:
srcbin2 = RawScale(input, mode="bipolar")
print(srcbin2())

Parameter containing:
tensor([[ 0.2690,  0.2620, -1.0000],
        [ 0.2695,  0.8709,  1.0000]], device='cuda:0')
