In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import torch
from UnarySim.sw.metric.metric import Correlation

In [3]:
corr = Correlation().cuda()

In [12]:
a = torch.tensor([0]).type(torch.int8).cuda()
b = torch.tensor([0]).type(torch.int8).cuda()

In [10]:
a = torch.tensor([0]).type(torch.int8).cuda()
b = torch.tensor([1]).type(torch.int8).cuda()

In [8]:
a = torch.tensor([1]).type(torch.int8).cuda()
b = torch.tensor([0]).type(torch.int8).cuda()

In [6]:
a = torch.tensor([1]).type(torch.int8).cuda()
b = torch.tensor([1]).type(torch.int8).cuda()

In [13]:
corr.Monitor(a,b)
print("d", corr.paired_00_d)
print("c", corr.paired_01_c)
print("b", corr.paired_10_b)
print("a", corr.paired_11_a)

cor = corr()
print(cor)

d Parameter containing:
tensor([1.], device='cuda:0')
c Parameter containing:
tensor([1.], device='cuda:0')
b Parameter containing:
tensor([1.], device='cuda:0')
a Parameter containing:
tensor([1.], device='cuda:0')
tensor([0.], device='cuda:0')


In [4]:
a = torch.tensor([0]).type(torch.int8).cuda()

In [4]:
a = torch.tensor([1]).type(torch.int8).cuda()

In [11]:
corr.Monitor(a)
print("d", corr.paired_00_d)
print("c", corr.paired_01_c)
print("b", corr.paired_10_b)
print("a", corr.paired_11_a)

cor = corr()
print("correlation", cor)

d Parameter containing:
tensor([0.], device='cuda:0')
c Parameter containing:
tensor([0.], device='cuda:0')
b Parameter containing:
tensor([1.], device='cuda:0')
a Parameter containing:
tensor([6.], device='cuda:0')
correlation tensor([0.], device='cuda:0')
