In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import torch
from UnarySim.sw.metric.metric import Stability


In [3]:
input = torch.tensor([-0.5,1.]).cuda()

In [4]:
stb = Stability(input, mode="bipolar", threshold=0.1).cuda()

In [5]:
a = torch.tensor([1,0]).type(torch.uint8).cuda()

In [7]:
a = torch.tensor([0,1]).type(torch.uint8).cuda()

In [8]:
stb.Monitor(a)
print(stb.err)
print(stb.stable_len)
print(stb.len)
print(stb.threshold)
print(stb())

stab lne: tensor([2., 2.], device='cuda:0')
Parameter containing:
tensor([ 0.5000, -1.0000], device='cuda:0')
tensor([2., 2.], device='cuda:0')
Parameter containing:
tensor([2.], device='cuda:0')
Parameter containing:
tensor([0.1000], device='cuda:0')
tensor([0., 0.], device='cuda:0')
