In [1]:
%load_ext autoreload
%autoreload 2

In [57]:
import torch
from UnarySim.sw.metric.metric import NormStability


In [58]:
normstb = NormStability(torch.tensor([[-0.5]]).cuda(), mode="bipolar", threshold=0.05).cuda()

In [59]:
a = torch.tensor([[1]]).type(torch.uint8).cuda()

In [60]:
a = torch.tensor([[0]]).type(torch.uint8).cuda()

In [61]:
print(a.size())

torch.Size([1, 1])


In [83]:
normstb.Monitor(a)
print(normstb())
print(normstb.threshold)
print(normstb.stability())
print(normstb.stability.len)
print("normstb.max_stab:", normstb.max_stab)
print(normstb.min_prob)
print(normstb.in_shape)

tensor([[0.]], device='cuda:0')
Parameter containing:
tensor([0.0500], device='cuda:0')
tensor([[0.]], device='cuda:0')
Parameter containing:
tensor([22.], device='cuda:0')
normstb.max_stab: tensor([[0.8750]], device='cuda:0')
Parameter containing:
tensor([[0.2250]], device='cuda:0')
torch.Size([1, 1])
