In [27]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [101]:
import torch
import numpy as np
import math
from UnarySim.sw.bitstream.gen import RNG, BSGen, BSRegen, SourceGen
from UnarySim.sw.bitstream.shuffle import SkewedSync
from UnarySim.sw.metric.metric import Correlation, ProgressiveError, Stability, NormStability


In [102]:
normstb = NormStability(torch.tensor([[-0.5]]), mode="bipolar", threshold=0.05)

In [136]:
a = torch.tensor([[1]]).type(torch.uint8)

In [104]:
a = torch.tensor([[0]]).type(torch.uint8)

In [105]:
print(a.size())

torch.Size([1, 1])


In [146]:
normstb.Monitor(a)
print(normstb.Report())
print(normstb.stability.Report())
print(normstb.max_stab)
print(normstb.stability.err)

tensor([[0.0533]])
tensor([[0.0500]])
tensor([[0.9375]])
tensor([[0.]])
