In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import torch
import numpy as np
import math
from UnarySim.sw.metric.metric import ProgressiveError


In [3]:
pp = ProgressiveError(torch.tensor([[0.5]]).cuda(), mode="unipolar").cuda()

In [14]:
a = torch.tensor([[1]]).cuda()

In [11]:
a = torch.tensor([[0]]).cuda()

In [15]:
pp.Monitor(a)
print(pp.one_cnt)
print(pp.len)

Parameter containing:
tensor([[2.]], device='cuda:0')
Parameter containing:
tensor([4.], device='cuda:0')


In [16]:
pp()

(Parameter containing:
 tensor([[0.5000]], device='cuda:0'), Parameter containing:
 tensor([[0.]], device='cuda:0'))