In [168]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [199]:
import torch
import UnarySim
from UnarySim.sw.bitstream.shuffle import SkewedSync


In [200]:
ss = SkewedSync(depth=3).cuda()

In [201]:
ss

SkewedSync()

In [202]:
print(ss.cnt)
print(ss.out_1)

Parameter containing:
tensor([1.0194e-38], device='cuda:0')
Parameter containing:
tensor([1.0194e-38], device='cuda:0')


In [219]:
a = torch.tensor([[0, 0]]).type(torch.uint8)
b = torch.tensor([[1, 1]]).type(torch.uint8)

In [214]:
a = torch.tensor([[1, 1]]).type(torch.uint8)
b = torch.tensor([[0, 0]]).type(torch.uint8)

In [209]:
a = torch.tensor([[1, 1]]).type(torch.uint8)
b = torch.tensor([[1, 1]]).type(torch.uint8)

In [206]:
a = torch.tensor([[0, 0]]).type(torch.uint8)
b = torch.tensor([[0, 0]]).type(torch.uint8)

In [221]:
a = a.cuda()
print(a)
b = b.cuda()
print(b)


tensor([[0, 0]], device='cuda:0', dtype=torch.uint8)
tensor([[1, 1]], device='cuda:0', dtype=torch.uint8)


In [228]:
ss(a,b)

(Parameter containing:
 tensor([[0, 0]], device='cuda:0', dtype=torch.uint8),
 tensor([[1, 1]], device='cuda:0', dtype=torch.uint8))