In [20]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [36]:
import torch
import numpy as np
import math
from UnarySim.sw.metric.metric import Stability


In [37]:
stb = Stability(torch.tensor([0.5,0]), mode="unipolar", threshold=0.1)

In [38]:
a = torch.tensor([1,0]).type(torch.uint8)

In [28]:
a = torch.tensor([0,1]).type(torch.uint8)

In [39]:
stb.Monitor(a)
print(stb.err)
print(stb.stable_len)
print(stb.len)
print(stb.Report())

tensor([0.5000, 0.0000])
tensor([1., 0.])
1.0
tensor([0., 1.])
