In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
import torch
import numpy as np
import math
from UnarySim.sw.metric.metric import Stability


In [4]:
stb = Stability(torch.tensor([-0.5,0]), mode="bipolar", threshold=0.1)

In [10]:
a = torch.tensor([1,0]).type(torch.uint8)

In [6]:
a = torch.tensor([0,1]).type(torch.uint8)

In [11]:
stb.Monitor(a)
print(stb.err)
print(stb.stable_len)
print(stb.len)
print(stb.Report())

tensor([0.0000, 0.5000])
tensor([3., 4.])
4.0
tensor([0.2500, 0.0000])
