In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import torch
from UnarySim.sw.stream.gen import RawScale

In [3]:
input = torch.randn([2, 3]).cuda()
print(input)
srcbin = RawScale(input, mode="unipolar", percentile=99).cuda()
print(srcbin)
print(srcbin())


tensor([[-0.3384, -1.1155, -0.1413],
        [ 1.6347,  0.5196,  0.6467]], device='cuda:0')
RawScale()
Parameter containing:
tensor([[0.2800, 0.0000, 0.3528],
        [1.0000, 0.5970, 0.6440]], device='cuda:0')


In [4]:
srcbin2 = RawScale(input, mode="bipolar")
print(srcbin2())

Parameter containing:
tensor([[-0.4349, -1.0000, -0.2915],
        [ 1.0000,  0.1891,  0.2815]], device='cuda:0')
