In [ ]:
%load_ext autoreload
%autoreload 2

In [2]:
import torch
from UnarySim.sw.stream.gen import RawScale

In [3]:
input = torch.randn([2, 3]).cuda()
print(input)
srcbin = RawScale(input, mode="unipolar", percentile=99).cuda()
print(srcbin)
print(srcbin())


tensor([[ 3.4595, -0.4636,  0.8816],
        [ 0.5827,  2.2747,  1.1333]], device='cuda:0')
RawScale()
Parameter containing:
tensor([[1.0000, 0.0000, 0.3411],
        [0.2638, 0.7013, 0.4062]], device='cuda:0')


In [4]:
srcbin2 = RawScale(input, mode="bipolar")
print(srcbin2())

Parameter containing:
tensor([[ 1.0000, -1.0000, -0.3142],
        [-0.4666,  0.3960, -0.1859]], device='cuda:0')
