In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import torch
import UnarySim
from UnarySim.sw.stream.shuffle_int import SkewedSyncInt

In [3]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

In [4]:
ss = SkewedSyncInt(depth=3).to(device)

In [5]:
a = torch.tensor([[0, 0]]).type(torch.float).to(device)
b = torch.tensor([[1, 1]]).type(torch.float).to(device)
out_a, out_b = ss(a,b)
print(out_a)
print(out_b)
print(ss.cnt)

tensor([[0., 0.]], device='cuda:0')
tensor([[1., 1.]], device='cuda:0')
Parameter containing:
tensor([[0., 0.]], device='cuda:0')


In [6]:
a = torch.tensor([[4, 4]]).type(torch.float).to(device)
b = torch.tensor([[0, 0]]).type(torch.float).to(device)
out_a, out_b = ss(a,b)
print(out_a)
print(out_b)
print(ss.cnt)

tensor([[0., 0.]], device='cuda:0')
tensor([[0., 0.]], device='cuda:0')
Parameter containing:
tensor([[4., 4.]], device='cuda:0')


In [7]:
a = torch.tensor([[4, 4]]).type(torch.float).to(device)
b = torch.tensor([[1, 1]]).type(torch.float).to(device)
out_a, out_b = ss(a,b)
print(out_a)
print(out_b)
print(ss.cnt)

tensor([[7., 7.]], device='cuda:0')
tensor([[1., 1.]], device='cuda:0')
Parameter containing:
tensor([[1., 1.]], device='cuda:0')


In [8]:
a = torch.tensor([[0, 0]]).type(torch.float).to(device)
b = torch.tensor([[0, 0]]).type(torch.float).to(device)
out_a, out_b = ss(a,b)
print(out_a)
print(out_b)
print(ss.cnt)

tensor([[0., 0.]], device='cuda:0')
tensor([[0., 0.]], device='cuda:0')
Parameter containing:
tensor([[1., 1.]], device='cuda:0')


In [9]:
a = torch.tensor([[4, 4]]).type(torch.float).to(device)
b = torch.tensor([[1, 1]]).type(torch.float).to(device)
out_a, out_b = ss(a,b)
print(out_a)
print(out_b)
print(ss.cnt)

tensor([[5., 5.]], device='cuda:0')
tensor([[1., 1.]], device='cuda:0')
Parameter containing:
tensor([[0., 0.]], device='cuda:0')


In [10]:
a = torch.tensor([[4, 4]]).type(torch.float).to(device)
b = torch.tensor([[0, 0]]).type(torch.float).to(device)
out_a, out_b = ss(a,b)
print(out_a)
print(out_b)
print(ss.cnt)

tensor([[0., 0.]], device='cuda:0')
tensor([[0., 0.]], device='cuda:0')
Parameter containing:
tensor([[4., 4.]], device='cuda:0')


In [11]:
a = torch.tensor([[4, 4]]).type(torch.float).to(device)
b = torch.tensor([[0, 0]]).type(torch.float).to(device)
out_a, out_b = ss(a,b)
print(out_a)
print(out_b)
print(ss.cnt)

tensor([[0., 0.]], device='cuda:0')
tensor([[0., 0.]], device='cuda:0')
Parameter containing:
tensor([[7., 7.]], device='cuda:0')


In [12]:
a = torch.tensor([[4, 4]]).type(torch.float).to(device)
b = torch.tensor([[0, 0]]).type(torch.float).to(device)
out_a, out_b = ss(a,b)
print(out_a)
print(out_b)
print(ss.cnt)

tensor([[0., 0.]], device='cuda:0')
tensor([[0., 0.]], device='cuda:0')
Parameter containing:
tensor([[7., 7.]], device='cuda:0')


In [13]:
a = torch.tensor([[2, 2]]).type(torch.float).to(device)
b = torch.tensor([[0, 0]]).type(torch.float).to(device)
out_a, out_b = ss(a,b)
print(out_a)
print(out_b)
print(ss.cnt)

tensor([[0., 0.]], device='cuda:0')
tensor([[0., 0.]], device='cuda:0')
Parameter containing:
tensor([[7., 7.]], device='cuda:0')
