In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import torch
from UnarySim.sw.stream.gen import RawScale

In [3]:
input = torch.randn([2, 3]).cuda()
print(input)
srcbin = RawScale(input, mode="unipolar", percentile=99).cuda()
print(srcbin)
print(srcbin())


tensor([[ 0.8144,  0.8125, -0.2147],
        [ 0.0104,  0.2086,  0.2939]], device='cuda:0')
RawScale()
Parameter containing:
tensor([[1.0000, 0.9982, 0.0000],
        [0.2144, 0.4081, 0.4915]], device='cuda:0')


In [4]:
srcbin2 = RawScale(input, mode="bipolar")
print(srcbin2())

Parameter containing:
tensor([[ 1.0000,  0.9962, -1.0000],
        [-0.5626, -0.1774, -0.0115]], device='cuda:0')
