In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import torch
import UnarySim
from UnarySim.sw.stream.shuffle import SkewedSync


In [3]:
ss = SkewedSync(depth=3).cuda()

In [4]:
print(ss.cnt)

Parameter containing:
tensor([0.], device='cuda:0')


In [5]:
a = torch.tensor([[0, 0]]).type(torch.float)
b = torch.tensor([[1, 1]]).type(torch.float)

In [6]:
a = torch.tensor([[1, 1]]).type(torch.float)
b = torch.tensor([[0, 0]]).type(torch.float)

In [7]:
a = torch.tensor([[1, 1]]).type(torch.float)
b = torch.tensor([[1, 1]]).type(torch.float)

In [8]:
a = torch.tensor([[0, 0]]).type(torch.float)
b = torch.tensor([[0, 0]]).type(torch.float)

In [9]:
a = a.cuda()
print(a)
b = b.cuda()
print(b)


tensor([[0., 0.]], device='cuda:0')
tensor([[0., 0.]], device='cuda:0')


In [10]:
print(ss(a,b))
print(ss.cnt)

(tensor([[0., 0.]], device='cuda:0'), tensor([[0., 0.]], device='cuda:0'))
Parameter containing:
tensor([[0., 0.]], device='cuda:0')
